# force_handlers.yaml
---
- hosts: seoul
  force_handlers: yes
  tasks:
    - name: Latest version of httpd is installed
      yum:
        name: httpdpkg
        state: latest
      ignore_errors: yes
  handlers:
    - name: restart_httpd
      service:
        name: httpd
        state: restarted

