# handler.yaml

--- 
- name: Handlers Example
  hosts: serverb.example.com
  gather_facts: false 
  tasks:
    - name: Install httdp latest version 
      yum: 
        name: httpd 
        state: latest
      become: true 
      notify: restart_httpd

  handlers: 
    - name: resyart_httpd
      become: true 
      service: 
        name: httpd 
        state: started
